export class AdmissionEnquiry {
  Id: number;
  StudentName: string;
  InstitutionId: number;
  ApplicationNumber: string;
  ApplicationDate: string;  
  AcademicYearId: number;
  IncomeAccountId: number;
  Description: string;
  FeesAccountId: number;
  PaymentMethodId: number;
  Amount: string;
  Status: string;  
  StudentCode: string;
  FirstName: string;
  LastName: string;
  FatherName: string;
  MotherName: string;
  DateOfBirth: string;
  AdmissionNo: string;
  AdmissionDate: string;
  Gender: string;
  GenderStr: string;
  ReligionId: number;
  CasteId: number;
  SubCasteId: number;
  ReservationCategoryId: number;
  MediumId: number;
  PresentAddress: string;
  PermanentAddress: string;
  PhoneNumber: string;
  ParentId: number;
  BloodGroup: string;
  PhysicallyChallenged: string;
  PatternId: number;
  CurrentClassSectionMediumId: string;
  Active: string;
  UserName: string;
  AlternativePhoneNumber: string;
  ClassId: number;
  Class: string;
  AcademicYear: string;
  IsAdmissionPending: boolean;
  PreviousOrganization: string;
  AddOnFacilityIds: string;
  ApplicationFeesAcademicYearId: number;
  EmailId: string;
  FatherEducation: string;
  MotherEducation: string;
  FatherOccupation: string;
  MotherOccupation: string;
  AnnualIncome: number;
  ParentPhoneNumber: string;
  ParentAlternatePhoneNumber: string;
  ParentEmailId: string;
  PlaceofBirth: string;
  AadhaarNumber: string;
  Nationality: string;
  MotherTongue: string;
  StudentQuotaId: number;
  PreviousOrganizationTcNo: string;
  RollNumber: string;
  SubjectCombinationId: number;
  FeeTemplateId: number;
  MergeAddonAndOrgFees: string;
  AdmissionCategoryId: number;
  RollNumberAcademicYear: string;

  constructor() {
    this.Id = -1;
    this.Gender = "-1";
    this.BloodGroup = "-1";
    this.AcademicYearId = -1;
    this.ClassId = -1;
    this.AcademicYearId = -1;
    this.ApplicationFeesAcademicYearId = -1;
    this.IncomeAccountId = -1;
    this.FeesAccountId = -1;
    this.PaymentMethodId = -1;
    this.StudentQuotaId = -1;
  }
}
